### ISSUE TITLE
Change License to GPL 3

### ISSUE THREAD

**Issue by trin94** [trin94/PySide6-project-template#14]
Hey @shadowkai0121, hey @Hobr

I'd like to change the license to GPL 3.0. This would allow me to implement the workaround described [here](https://github.com/trin94/framelesswindow-arrow-keys-windows) and [here (Qt bug report)](https://bugreports.qt.io/browse/QTBUG-109672).
I need your agreement to implement the license change :)

Happy new year!

**Comment by Hobr** [comment]
Happy new year! I agree, although i just contribute one line change:)

**Comment by trin94** [comment]
@shadowkai0121 Have you thought about it?

The license change will allow me to add code that is currently under the GPL 3.0. This code fixes window snapping (WinKey + Arrow Buttons) and also adds drop shadow on Windows. Once there's an official fix upstream, I would love to change it back to LGPL 3.0 again.

**Comment by shadowkai0121** [comment]
I'm sorry I only noticed this message now. I think I don't have any problem with it.

**Comment by trin94** [comment]
Hey @shadowkai0121! All good, don't worry!

@shadowkai0121 @Hobr Thanks for agreeing. I've made the changes. Best regards
