### ISSUE TITLE
Failure to boot after packaging with nuitka under Windows11.

### ISSUE THREAD

**Issue by 0xlitf** [trin94/PySide6-project-template#27]
Hi Elias, thank you for this project!

Everything works well, but having some packaging problems with nuitka, my script is:

`./venv/Scripts/nuitka.cmd --standalone --windows-disable-console --show-progress --show-memory --enable-plugin=pyside6 --windows-icon-from-ico=./logo.ico main.py`

Then, in folder `main.dist`, when open `main.exe`, nothing happens.

So what can I do to package the project?

Any help would be appreciated!

**Comment by trin94** [comment]
Hi :smiley: 

You can use `--windows-console-mode=attach` in recent nuitka versions. This should allow you to get a stack trace when running it from a terminal.

At a first glance, I think that nuitka does not pick up the qml files. Nuitka should log that it picked up the qml files. If you don't see it when executing, try adding

```shell
--include-qt-plugins=all --include-qt-plugins=qml
```
to your command. 

I remember I ran into this issue when I migrated [mpvQC](https://github.com/mpvqc/mpvQC/tree/main) to nuitka. You can find the command I am using for mpvQC [here](https://github.com/mpvqc/mpvQC/blob/b91b91dce7932fce8c128248441ef410db695efe/.github/workflows/release.yml#L179).

Let me now if that solved it for you :+1: 

Best,  
Elias

**Comment by 0xlitf** [comment]
Oh, amazing, It works!
Thank you, Elias!

`nuitka.cmd --standalone --windows-disable-console --show-progress --show-memory --enable-plugin=pyside6 --windows-icon-from-ico=./logo.ico --include-qt-plugins=all --include-qt-plugins=qml
 main.py`
