### ISSUE TITLE
DragHandler & doubleclick

### ISSUE THREAD

**Issue by valq7711** [trin94/PySide6-project-template#6]
Hi! Thanks for the great stuff!

I ran into an issue with the double click event, after spending a day i figured out it was a DragHandler problem (used for resizing) - it seems to intercept all double clicks so the event doesn't propagate to the target, don't know if it's a bug or a feature

**Comment by trin94** [comment]
Hey, thank you for the feedback!

Apperantly, this is a bug / regression that was fixed in 6.4.0: https://bugreports.qt.io/browse/QTBUG-102625. On 6.3.x I could reproduce the error but on 6.4.0 it's working.  
Please upgrade to PySide 6.4.0 and try again :smiley:
